name: Flutter iOS CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Ruby (needed for fastlane)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      # 3. Select correct Xcode version
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      # 4. Install Ruby dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # 5. Install CocoaPods for iOS
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      # 6. Build & Upload to TestFlight
      - name: Build and upload to TestFlight
        run: bundle exec fastlane beta
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
