name: Flutter iOS CI/CD

on:
  workflow_dispatch:   # Run only when manually triggered

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Setup Ruby (needed for Fastlane)
      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Build and Upload to TestFlight
        run: |
          cd ios
          fastlane beta
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

