name: Flutter Android CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:
      ANDROID_HOME: /Users/runner/Library/Android/sdk
      FLUTTER_HOME: /opt/hostedtoolcache/flutter/stable-3.22.0-x64

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v4

      # 2. Install Java 17 (compatible with Gradle 7.x/8.x)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get


      # 6. Build Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # 6. Build Android App Bundle (Play Store)
      - name: Build Android App Bundle
        run: flutter build appbundle --release

      # 7. Upload APK/AAB as GitHub workflow artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      # 8. Deploy to Google Play Internal Testing
      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT }}
          packageName: com.ito.onlineexam.app   # 🔹 replace with your actual package name
          releaseFile: build/app/outputs/bundle/release/app-release.aab
          track: internal
